# Generated by Django 5.0.1 on 2025-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurefeedbackmap',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
