# Generated by Django 5.0.1 on 2025-12-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_featurefeedbackmap_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='ai_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='last_ai_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
